### ISSUE TITLE
Device Scanner Checklist

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#1715]
What's TODO:
- [x] Merge with master
- [x] Reimplement stuff removed during removal of `StorageResource` (mostly getting device types from Python)
- [x] Switch the rest of code base from `Volume` / `VolumeNode` to `Device` / `DeviceHost` tables
- [ ] Implement UI of device hosts (not just ids and hosts)
- [ ] Implement full UI of devices (not just ids)
- [ ] Implement `usable_for_lustre` (currently always `false`)
- [ ] Figure out the removal (mark devices as deleted in DB and alert about devices that are suddenly missing)
- [ ] Fix or remove tests that depend on old code

List of issues:
- [x] When adding an OSS server, job_scheduler stops working w/o any error and restarts
- [ ] When detecting a monitored FS, there's an error in agent due to unknown device type
  
  ```
  [2020-03-27 11:40:40,850: ERROR/job_scheduler] Job 21 step 0 encountered an agent error: Traceback (most recent call last):
    File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/action_runner.py", line 182, in run
      self.action, agent_daemon_context, self.args
    File "/usr/lib/python2.7/site-packages/chroma_agent/plugin_manager.py", line 321, in run
      return fn(**args)
    File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/detect_scan.py", line 205, in detect_scan
      local_targets = LocalTargets(settings["target_devices"])
    File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/detect_scan.py", line 80, in __init__
      block_device = BlockDevice(device["type"], device["path"])
    File "/usr/lib/python2.7/site-packages/iml_common/blockdevices/blockdevice.py", line 56, in __new__
      raise cls.UnknownBlockDevice("DeviceType %s unknown" % device_type)
  UnknownBlockDevice: u'DeviceType mpath_member unknown'
  ```

**Comment by mkpankov** [comment]
Places that need to be modified:

- [`JobScheduler.create_filesystem`](https://github.com/whamcloud/integrated-manager-for-lustre/blob/240562dbfe475004abc012dced5b1a99a417f9dc/chroma_core/services/job_scheduler/job_scheduler.py#L1266)
- `JobSchedulerClient` and API for `create_filesystem`

**Comment by mkpankov** [comment]
Given there's quite a lot of places and it's hard to test them in isolation, I'm thinking of doing a "migration period" where things that want `Volume` will also refer to `Device` and same thing for `VolumeNode` / `DeviceHost`. Then the implementation will be gradually changed to use the new tables and lastly the old ones will be removed.

**Comment by mkpankov** [comment]
Smooth migration won't work since I removed `LearnDevicesStep` and `UpdateDevicesStep` because they depended on `AgentDaemonRpcInterface` that got removed.

**Comment by jgrund** [comment]
> Given there's quite a lot of places and it's hard to test them in isolation, I'm thinking of doing a "migration period" where things that want Volume will also refer to Device and same thing for VolumeNode / DeviceHost. Then the implementation will be gradually changed to use the new tables and lastly the old ones will be removed.

Given the state of this work, I think it's better if we just switch over everything at once. We won't gain anything by waiting at this point.

**Comment by mkpankov** [comment]
I have rewritten all the code for points 2 and 3 in the issue description. Didn't test, nothing works probably.

**Comment by mkpankov** [comment]
Current issues:
- [ ] When adding an OSS server, job_scheduler stops working w/o any error and restarts
- [ ] When detecting a monitored FS, there's an error in agent due to unknown device type

**Comment by mkpankov** [comment]
Current version of Device Hosts UI with `local` and `paths` fields. FS itself is unmounted, this is after cluster reload and `import-pools` provision
![Peek 2020-04-01 16-10](https://user-images.githubusercontent.com/393741/78140925-6d0dda80-7433-11ea-9d33-0e3eeaf61402.gif)

**Comment by mkpankov** [comment]
Unmounting / mounting reflects in the UI:
![Peek 2020-04-02 11-50](https://user-images.githubusercontent.com/393741/78229308-7b620200-74d8-11ea-9335-e81baed8b494.gif)
