### ISSUE TITLE
Get SSI tests running on Windows/Cygwin/Vagrant

### ISSUE THREAD

**Issue by tanabarr** [whamcloud/integrated-manager-for-lustre#201]
We want contributors to be able to develop on Windows, this means being able to run IML tests on Windows.

HOWTO document is on the [wiki](https://github.com/intel-hpdd/intel-manager-for-lustre/wiki/Running-IML-tests-on-HPC-cluster-with-Windows,-Cygwin-and-Vagrant)

There are a number of changes required to make this work.

---
- [ ] Create wiki page to detailed instructions
  - [x] Add the basic package installation list for Cygwin/Vagrant/Virtualbox
  - [x] Add instructions regarding free space requirements
  - [x] Add instructions regarding compiling pdsh on Cygwin
  - [x] Add instructions regarding use of host-only interfaces in Virtualbox
  - [ ] Add instructions on fetching the required test target packages
  - [ ] Add instructions on how to run tests and where to find output
---
- [ ] Update Makefile to work on Cygwin
  - [x] Fix in compatibility with Windows Virtualbox version and VBoxManage --comment option #196
  - [x] Workaround vagrant failure "stdout is not a tty" on cygwin when output is file or pipe
    - [x] Add instructions to wiki warning of bug in vagrant version 1.9.7 and need to downgrade to 1.9.6
  - [x] Perform libvirt specific configuration only when used as the vagrant provider #199 
  - [x] Fix connection issues between host and vms
    - [x] Add instructions to wiki warning of potential interference with .ssh/config file
    - [ ] As using vagrant ssh config, remove the hosts file entries as they are unnecessary
  - [ ] Get SSI tests to run to completion
    - [x] Get cluster setup scripts to run successfully
    - [x] Fix cluster configuration json files to work with Virtualbox
      - [ ] Fix ring1_iface parameter provided by provisioner json config #211
---
- [ ] Improve experience of running automated tests
  - [x] Enable reset of cluster without having to manually confirm removal of each VM ~~#197~~
  - [ ] Make power control work with vbox so that one guest can fence/power cycle another #207
  - [x] Add target to base Makefile to fetch current master build (convenience for running tests) #203
    - [x] Add capacity to fetch chroma-integration-tests RPM package from build for SSI tests #203

**Comment by brianjmurrell** [comment]
Probably need to add a point about making _power control_ work such that one guest can power cycle another.

Rather than having the user compile _pdsh_ can we not just supply the binary that we are compiling  anyway?  Or is there a project we can contribute to that supplies Cygwin binaries?  Maybe we can submit an enhancement to Cygwin itself to build and include _pdsh_ in it's distribution?

**Comment by tanabarr** [comment]
can do both,  first one done
