### ISSUE TITLE
Create Actions for Stratagem - Client Side

### ISSUE THREAD

**Issue by utopiabound** [whamcloud/integrated-manager-for-lustre#857]
### Description 

Create iml-agent action plugins to integrate with stratagem runners

## TODO
- [x] Add file-input option to stratagem runners: `stratagem-runners/`
- [x] Create action plugins: `iml-agent/src/action_plugins/` ([example](https://github.com/whamcloud/integrated-manager-for-lustre/blob/4c5a21de16a5734d61496b3c026e537ed8a27c88/iml-agent/src/action_plugins/manage_stratagem.rs#L40-L54))
- [x] Create CLI actions: `iml-agent/src/cli.rs`
- [x] Add /mailbox reader
